### ISSUE TITLE
Mark some dependencies as devDependencies

### ISSUE THREAD

**Issue by geozaur** [brendanmorrell/eslint-plugin-styled-components-a11y#10]
Hello! 👋 

Thank you very much for contributing with this awesome plugin!  🙏 
I really hope it will gain more traction!

I've seen that some dependencies (like jest and nodemon) could be marked as developer dependencies.
What do you think?

**Comment by brendanmorrell** [comment]
Good catch. That was accidental. I'll switch those to dev dependencies.Thanks!

**Comment by brendanmorrell** [comment]
Just published version 0.0.17 with a significantly trimmed down dependency list. Thanks!

**Comment by geozaur** [comment]
Thank you so much for the quick response! 🙏
