### ISSUE TITLE
No-AutoFocus Rule isn't Detected for all Styled Components

### ISSUE THREAD

**Issue by SudharakaP** [brendanmorrell/eslint-plugin-styled-components-a11y#16]
Working on fixing the accessibility issues on open-collective as detected by this plugin I noticed that the [no-auto-focus rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md) isn't somehow being reported for all components. It was reported for one component but not for every component that is being used in this repo. 

The relevant PR where I fixed all the accessibility issues reported by this plugin is here; https://github.com/opencollective/opencollective-frontend/pull/5961. Notice that only one single [auto-focus attribute was reported](https://github.com/opencollective/opencollective-frontend/pull/5961/commits/f646eab9032111f8cf941bee525b74b2d2c6d3b1). But doing a global search on the repo shows that many other components use the auto-focus attribute and all of these I think should fall under the [a11y rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md) rule as it simply says no-autofocus. 

Reference PR: https://github.com/opencollective/opencollective-frontend/pull/5961

cc: @brendanmorrell

**Comment by brendanmorrell** [comment]
Thanks for the examples. I can take a look soon.

**Comment by SudharakaP** [comment]
@brendanmorrell : Sure no rush; I just opened a couple of issues so that you know; hope it helps improve the plugin further. 😄

**Comment by brendanmorrell** [comment]
Absolutely. Appreciate it.

>

**Comment by brendanmorrell** [comment]
@SudharakaP Took a look at this briefly tonight. I have thus far only looked at one example where the error was not called out with the linter (the example you posted (above)[https://github.com/opencollective/opencollective-frontend/pull/5961/commits/f646eab9032111f8cf941bee525b74b2d2c6d3b1] with `components/StyledInputTags.js`). At least in that file, the reason the autofocus attribute is not being called out is that that component is a styled component that is created after applying the `styled(` function to an imported component. As of now, imports aren't supported, so anything based off of an imported component will not have the a11y linting rules applied to it.  Just did a quick search of your repo, and the first 6 or so examples I saw of autofocus all were in files where the component in question was imported not defined, so I assume that is the reason you aren't seeing the rule fire. Does that make sense? also, are there examples where it doesn't fire correctly even on components defined within the same file?

**Comment by brendanmorrell** [comment]
Yeah. Looked again, and essentially all of these seem to be components defined in other files and then imported into a different file which actually calls them in JSX. So that's the reason they aren't surfacing the warning

**Comment by SudharakaP** [comment]
> @SudharakaP Took a look at this briefly tonight. I have thus far only looked at one example where the error was not called out with the linter (the example you posted [above](https://github.com/opencollective/opencollective-frontend/pull/5961/commits/f646eab9032111f8cf941bee525b74b2d2c6d3b1) with `components/StyledInputTags.js`). At least in that file, the reason the autofocus attribute is not being called out is that that component is a styled component that is created after applying the `styled(` function to an imported component. As of now, imports aren't supported, so anything based off of an imported component will not have the a11y linting rules applied to it. Just did a quick search of your repo, and the first 6 or so examples I saw of autofocus all were in files where the component in question was imported but not defined, so I assume that is the reason you aren't seeing the rule fire. Does that make sense? Or are there examples where it doesn't fire correctly even on components defined within the same file?

@brendanmorrell : Thanks much for looking into this. Yes, it makes perfect sense. Hopefully this library can support imported components in the future. 😉 But anyways, thanks for clarifying. 😄

**Comment by brendanmorrell** [comment]
It's definitely something I would like to support in the future. Let me
know if you see any instances where the rule is misfiring when the
component is defined within the same file. Thanks again!
