### ISSUE TITLE
Using withComponent API in Styled-Components doesn't seem to Trigger Warnings

### ISSUE THREAD

**Issue by SudharakaP** [brendanmorrell/eslint-plugin-styled-components-a11y#17]
I am not sure if this plugin supports the [withComponent API](https://styled-components.com/docs/api#withcomponent) yet, but it seems that when a label is rendered using the `withComponent` API it doesn't trigger the usual a11y errors. Although the newer way of using `as` to do this will trigger the warning. 

I've created a PR to demonstrate this at, https://github.com/opencollective/opencollective-frontend/pull/6007

Notice that when I use a component which uses `withComponent` API it doesn't seem to give the errors, although I think it should since they are still labels. 😄 

cc: @brendanmorrell

**Comment by brendanmorrell** [comment]
That is correct. `withComponent` is not currently supported. It's possible I could add it in, but considering it is a candidate for deprecation, I haven't wanted to spend too much time on it. If time permits, I can take a look at how difficult it would be, though.
