### ISSUE TITLE
label-has-associated-control Rule is Triggered Even when Associated Control is Present

### ISSUE THREAD

**Issue by SudharakaP** [brendanmorrell/eslint-plugin-styled-components-a11y#18]
Integrating this plugin to our code base there was one occasion where the `a11y/label-has-associated-control` rule is triggered even when an associated control was present just below the label. We couldn't understand exactly why this is the case? 🤔 Maybe this plugin couldn't understand the underlying `react.input` as a proper `input` control? 

Associated PR Discussion: https://github.com/opencollective/opencollective-frontend/pull/5961#discussion_r594948372

**Comment by brendanmorrell** [comment]
Interesting. The code looks normal. I'll try and take a look soon. Thanks for pointing it out

**Comment by SudharakaP** [comment]
> Interesting. The code looks normal. I'll try and take a look soon. Thanks for pointing it out

You are welcome; let us know if there's anything you need from our end. 👍🏽

**Comment by brendanmorrell** [comment]
Sounds good. Thanks for pointing it out.

**Comment by gertsonderby** [comment]
I'm running into this now myself: I have a simple set of a styled `label` wrapping a styled `input`, and this rule is triggered.

**Comment by brendanmorrell** [comment]
This rule does seem to be imperfect at the moment. I am traveling the next couple months, but when I get back I can take a closer look and see if I can find anything

**Comment by 42tte** [comment]
Since you state this plugin is meant to be the equivalent eslint-plugin-jsx-a11y you should probably not extend eslint-config-airbnb/rules/react-a11y since the latter apparently have at least one different rule.

**Comment by brendanmorrell** [comment]
Hey Kristoffer. I think that makes sense. Traveling for the next month, so
not gonna get to it yet, but feel free to submit a PR in the meantime if
you'd like to. Cheers
