### ISSUE TITLE
Upgrade eslint-config-airbnb to latest to correct incorrect eslint peer dep

### ISSUE THREAD

**Issue by mcmxcdev** [brendanmorrell/eslint-plugin-styled-components-a11y#27]
When installing `eslint-plugin-styled-components-a11y`, this peer dependency warning is thrown on yarn install:
 
`warning "eslint-plugin-styled-components-a11y > eslint-config-airbnb > eslint-config-airbnb-base@13.2.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".`

`eslint-config-airbnb` v18 allows ESLint ^7 in peerDeps, which would resolve this warning.

**Comment by brendanmorrell** [comment]
I'll take a look. Thanks for pointing that out.
