### ISSUE TITLE
Inform users of semver version changes

### ISSUE THREAD

**Issue by mcmxcdev** [brendanmorrell/eslint-plugin-styled-components-a11y#28]
This project currently doesn't have any way of finding out what changed between versions except for going through the commit history. 

Adding a `CHANGELOG.md` or using the tag/releases functionality on GitHub would make it easier for consumers of the library to know what changed.

**Comment by brendanmorrell** [comment]
Good call. I'll try and add one this weekend. Thanks.

**Comment by brendanmorrell** [comment]
@mcmxcdev added a changelog before publishing this most recent version. Thanks for the suggestion!
