### ISSUE TITLE
Styled components defined in a object

### ISSUE THREAD

**Issue by pawelglosz** [brendanmorrell/eslint-plugin-styled-components-a11y#38]
Hello @brendanmorrell,

First of all, thank you for this great plugin!

In my project, I'm using the following pattern for defining styled components:
```
const S = { Button: styled.button`` };
<S.Button onClick={() => null} />;
```

Would you be interested in supporting such case in your library? I've created a proposal solution, so I can make a PR to your repository if you'd be interested.

**Comment by brendanmorrell** [comment]
That's a new pattern for me, but I'd definitely be interested in the
proposal PR and would like to support it. If I can take a look, I'll try
and get it in/make any tweaks it may need asap.

Thanks!

**Comment by pawelglosz** [comment]
Great! Can I have write access to the repository to create a PR?

**Comment by brendanmorrell** [comment]
Hello!

Pretty sure you just need to for the repo and then you can submit the PR
request for review. If I'm incorrect about that, let me know, and I'll look
into it. And thanks for being willing to contribute!
