### ISSUE TITLE
regarding airbnb rules inclusion

### ISSUE THREAD

**Issue by twig-atl** [brendanmorrell/eslint-plugin-styled-components-a11y#4]
Using the configurations provided by `eslint-plugin-styled-components-a11y` adds a bunch of unrelated rules from the airbnb configuration such as whitespacing, etc.

```
 configs: {
    recommended: {
      plugins: ['styled-components-a11y'],
      extends: ['eslint-config-airbnb'],
```

Since this is an a11y specific linter, it should restrict itself to either recommending via installation documentation or only importing the relevant rules from [airbnb's files](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js)

**Comment by twig-atl** [comment]
Created a PR for it https://github.com/brendanmorrell/eslint-plugin-styled-components-a11y/pull/5

**Comment by brendanmorrell** [comment]
good call. Thanks for the pr, @twig-atl
