### ISSUE TITLE
Memory leak on project build!

### ISSUE THREAD

**Issue by mario-iliev** [brendanmorrell/eslint-plugin-styled-components-a11y#40]
Hi guys!
After jumping from version 0.0.34 to 0.0.39 our app couldn't finish the build process and Jenkins was running out of memory.
It took me day and a half to locate the problematic packages because I updated several packages at once that day. So I started updating one by one. Sadly there are no errors or anything, just stuck forever in the building process.
Try to reproduce by removing your node_modules and installing everything from scratch with latest version.

**Comment by brendanmorrell** [comment]
Thank you @mario-iliev and apologies for the issue. I just reverted the offending PR and published a new version (0.0.40). Please upgrade to 0.0.40 and the issue should be resolved. The broken versions (0.0.35-0.0.39) have also all been marked as deprecated.
