### ISSUE TITLE
control-has-associated-label is disabled in configs

### ISSUE THREAD

**Issue by EvgenyOrekhov** [brendanmorrell/eslint-plugin-styled-components-a11y#43]
https://github.com/brendanmorrell/eslint-plugin-styled-components-a11y/blob/612021b4f091c4f929e3753bafa1609f90fba3ca/src/index.js#L62-L63

Is that intentional? Is there some problem with this rule?

**Comment by brendanmorrell** [comment]
Good question. I either was confusing that with the deprecated [label-has-for-rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-for.md), or possibly the nesting component of those rule was misfiring in some way with styled components. Can't remember. I can try to look into it later this week. May also just have been an oversight.

**Comment by brendanmorrell** [comment]
This obviously slipped my mind, but I noticed it again today, and have an answer for you. The rule sets are all intended to mimic those of jsx-a11y, and that is the recommended rule configuration used [there](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/index.js#L66).
