### ISSUE TITLE
Add support for `styled('element')` syntax

### ISSUE THREAD

**Issue by EvgenyOrekhov** [brendanmorrell/eslint-plugin-styled-components-a11y#47]
For example, MUI uses `styled('element')` instead of `styled.element`, but the functionality is mostly the same.
It would be awesome if this plugin could support `styled('element')` syntax.

**Comment by brendanmorrell** [comment]
That’s a good point. That is an oversight definitely. I believe when I
first made this that was a syntax I hadn’t encountered but I actually use
it all the time with emotion styled.Definitely feasible. Seems like it
wouldn’t be too bad to implement. I’ll try to take a look within the next
few days, and give you a likely ETA.

**Comment by brendanmorrell** [comment]
Made this^^ change, and new version incoming. Got locked out of my npm account due to losing my 2fa device, but I should have it published in the next few days when I regain access.
